import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const { to, subject, projectData, conversationSummary } = await request.json();

    // Format the project data as HTML
    const dataRows = Object.entries(projectData)
      .filter(([, value]) => value)
      .map(
        ([key, value]) =>
          `<tr><td style="padding: 8px; border: 1px solid #e2e8f0; font-weight: 600; background: #f8fafc;">${formatFieldName(key)}</td><td style="padding: 8px; border: 1px solid #e2e8f0;">${value}</td></tr>`
      )
      .join('');

    const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1e293b; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #003B75; border-bottom: 2px solid #00A3E0; padding-bottom: 10px; }
    h2 { color: #003B75; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Investor Deck - Project Data</h1>
    <p>Here's the information collected for your investor deck:</p>

    <h2>Project Details</h2>
    <table>
      ${dataRows || '<tr><td>No data collected yet</td></tr>'}
    </table>

    <div class="footer">
      <p>Generated by Investor Deck Generator</p>
      <p>You can use this data to create your investor presentation.</p>
    </div>
  </div>
</body>
</html>
`;

    // For now, we'll use a simple approach - you can integrate with Resend, SendGrid, etc.
    // Check if RESEND_API_KEY is available
    const resendKey = process.env.RESEND_API_KEY;

    if (resendKey) {
      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${resendKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: 'Investor Deck <noreply@resend.dev>',
          to: [to],
          subject: subject || 'Your Investor Deck Project Data',
          html,
        }),
      });

      if (response.ok) {
        return NextResponse.json({ success: true, message: 'Email sent successfully' });
      } else {
        const error = await response.text();
        console.error('Resend error:', error);
        return NextResponse.json({ success: false, error: 'Failed to send email' }, { status: 500 });
      }
    }

    // If no email service configured, return the data for download
    return NextResponse.json({
      success: true,
      message: 'Email service not configured. Data prepared for download.',
      html,
      fallback: true,
    });
  } catch (error) {
    console.error('Email API error:', error);
    return NextResponse.json({ success: false, error: 'Failed to process request' }, { status: 500 });
  }
}

function formatFieldName(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (str) => str.toUpperCase())
    .trim();
}
